language: rust
rust:
  - 1.21.0
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test
#after_success: |
#  [ $TRAVIS_BRANCH = master ] &&
#  [ $TRAVIS_PULL_REQUEST = false ] &&
#  [ $TRAVIS_RUST_VERSION = nightly ] &&
#  ssh-agent ./ci/deploy.sh
notifications:
  email:
    on_success: never
branches:
  only:
    - master
