[package]
name = "bint"
version = "0.1.0"
authors = ["Christoph <ignatz@gmail.com>"]
repository = "https://github.com/folkengine/bint-rs.git"
homepage = "https://github.com/folkengine/bint-rs"
license = "GPL3"
readme = "README.md"
documentation = "http://killercup.github.io/hsl-rs/"
description = "Represent colors in HSL and convert between HSL and RGB."

[dependencies]
clippy = {version = "*", optional = true}

[features]
default = []
