[package]
name = "bint"
version = "0.1.0"
authors = ["Christoph <gaoler@electronicpanopticon.com"]
repository = "https://github.com/folkengine/bint-rs.git"
homepage = "https://github.com/folkengine/bint-rs"
license = "MIT"
readme = "README.md"
# documentation = ""
description = "Bounded Integer in Rust."

[dependencies]
clippy = {version = "0.0.302", optional = true}

[features]
default = []
